######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 5 16:51:10 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/realtime/include
QT += network

# Input
HEADERS += stimdaemon.h \
           ../octopus-stim.h \
           ../fb_command.h \
           ../cs_command.h \
           ../patt_datagram.h
SOURCES += main.cpp
