######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 4 13:52:18 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
