######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 5 19:24:58 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
