######################################################################
# Automatically generated by qmake (2.01a) Fri May 22 10:52:11 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/realtime/include
QT += network

# Input
HEADERS += acqdaemon.h \
           acqthread.h \
           ../octopus-acq.h \
           ../fb_command.h \
           ../cs_command.h
SOURCES += main.cpp
